########################################
### Template Type: aspnet-template   ###
### Template Version: 3.4.0          ###
### Author: hfrances                 ###
### Date: 30/03/2026                 ###
########################################

parameters:
  # Indica si se debe publicar el paquete en Universal Packages.
  # - auto: Se publica si la rama es master o main.
  # - true: Se publica siempre.
  # - false: No se publica.
  - name: Deploy
    type: string
    values:
      - auto
      - true
      - false
    default: false
  # Indica si se debe ejecutar SonarQube para análisis de código.
  # - disabled: No se ejecuta SonarQube.
  # - auto: Se ejecuta SonarQube si la rama es master, main, staging.
  # - true: Se ejecuta SonarQube siempre.
  - name: Analyze
    type: string
    values:
      - disabled
      - auto
      - true
      - false
    default: disabled
  # Indica si se deben ejecutar pruebas unitarias y generar informes de cobertura.
  # - disabled: No se ejecutan pruebas unitarias.
  # - auto: Se ejecutan pruebas unitarias si hay proyecto de test.
  - name: Test
    type: string
    values:
      - disabled
      - auto
    default: auto
  # Patrón de búsqueda del proyecto principal. Por defecto, busca el primer proyecto en la solución.
  - name: Solution
    type: string
    default: '*.sln'
  # Indica si debe reemplazar la versión siempre o si debe hacerlo solamente cuando coincide con el proyecto principal.
  - name: ForceVersion
    type: boolean
    default: false
  # Indica si los binarios deben publicarse en el Universal Packages.
  # - true: Publicar en el Universal Packages.
  #         Requiere variable 'Deploy' con valor 'true' o 'auto' y que la rama sea master o main.
  # - false: No publicar en el Universal Packages.
  - name: SupportsUniversalPackages
    displayName: "Supports universal packages"
    type: boolean
    default: false
  # Indica si el proyecto soporta contenedores Docker.
  # - true: Soporta contenedores Docker.
  #         Requiere variable 'ContainerRegistry' con el nombre del registro de contenedores (previamente configurado en los conectores) y 'ContainerName' con el nombre del contenedor.
  #         Requiere variable 'Deploy' con valor 'true' o 'auto'. Funciona con cualquier rama.
  # - false: No soporta contenedores Docker.
  - name: SupportsContainers
    displayName: "Supports container"
    type: boolean
    default: true
  # Indica si se debe comprobar si existen cambios afectados antes de compilar o publicar.
  # - true: Busca la última ejecución compilada y publicada con éxito del mismo pipeline y rama, y usa dotnet-affected para decidir qué hacer.
  # - false: No realiza comprobaciones y mantiene el comportamiento anterior.
  - name: PublishChangeDetection
    displayName: "Publish change detection"
    type: boolean
    default: true

variables:
  - name: BuildParameters.RestoreBuildProjects
    value: "**/${{ parameters.Solution }}"
  - name: BuildParameters.Solution
    value: ${{ parameters.Solution }}
  - name: Solution.FullName
    value: ''
  - name: BuildParameters.TestProjects
    value: |-
      **/*Test.??proj
      **/*Tests.??proj
      !**/*.Test.*.??proj
      !**/*.Tests.*.??proj
  - name: BuildParameters.ProjectKey
    value: $(Build.DefinitionName)
  - name: BuildParameters.ProjectName
    value: $(BuildParameters.ProjectKey)
  - name: BuildParameters.OutputDirectory
    value: '' # '' | '<dir>' | $[variables['System.PhaseName']]
  - name: BuildParameters.OutputFile
    value: ''
  - name: BuildConfiguration
    value: 'Release'
  - name: Deploy
    value: ${{ parameters.Deploy }}
  - name: PublishEnabledBranches
    value: |
      refs/heads/master
      refs/heads/main
  - name: DockerEnabledBranches
    value: |
      refs/heads/master
      refs/heads/main
      refs/heads/staging
  - name: SonarQubeEnabledBranches
    value: $(PublishEnabledBranches)
  - name: PublishEnabled
    value: $[iif(or(eq(variables.Deploy, 'true'), and(eq(variables.Deploy, 'auto'), contains(format('\n{0}\n', variables['PublishEnabledBranches']), format('\n{0}\n', variables['Build.SourceBranch'])))), 'true', 'false')]
  - name: PublishDocker
    value: $[iif(and(eq('${{ parameters.SupportsContainers }}', 'true'), ne(variables['ContainerRegistry'], ''), ne(variables['ContainerName'], ''), or(eq(variables.Deploy, 'true'), and(eq(variables.Deploy, 'auto'), contains(format('\n{0}\n', variables['DockerEnabledBranches']), format('\n{0}\n', variables['Build.SourceBranch']))))), 'true', 'false')]
  - name: Analyze
    value: ${{ parameters.Analyze }}
  - name: SonarQubeEnabled
    value: $[or(eq(variables.Analyze, 'true'), and(eq(variables.Analyze, 'auto'), contains(format('\n{0}\n', variables['SonarQubeEnabledBranches']), format('\n{0}\n', variables['Build.SourceBranch']))))] # TODO: Remove 'refs/heads/feature/net10' when not needed
  - name: TestEnabled
    value: $[ne('${{ parameters.Test }}', 'disabled')]
  - name: SupportedFrameworks
    value: "10.0;9.0;8.0;7.0;6.0;5.0;3.1"
  - name: ForceVersion
    value: ${{ parameters.ForceVersion }}
  - name: ExternalFeedValue
    value: $[iif(ne(variables['ExternalFeed'], ''), variables['ExternalFeed'], '')]

jobs:
  - template: ../jobs-templates/prepare-dotnet-job.yml@azure-pipelines-repo
    parameters:
      solutionPattern: '$(BuildParameters.Solution)'
      publishChangeDetection: ${{ parameters.PublishChangeDetection }}
      publishExtraMode: aspnet

  - job: Build
    displayName: Build and push
    dependsOn: Prepare
    condition: and(succeeded(), eq(dependencies.Prepare.outputs['ExportPreparation.BuildParameters.HasAffectedBuildProjects'], 'true'))
    variables:
      - name: Solution.FullName
        value: $[ dependencies.Prepare.outputs['ExportPreparation.SolutionFullName'] ]
      - name: Solution.NugetFeedToUse
        value: $[ dependencies.Prepare.outputs['ExportPreparation.SolutionNugetFeedToUse'] ]
      - name: Solution.NugetConfig
        value: $[ dependencies.Prepare.outputs['ExportPreparation.SolutionNugetConfig'] ]
      - name: MainProject.FullName
        value: $[ dependencies.Prepare.outputs['ExportPreparation.MainProjectFullName'] ]
      - name: MainProject.Version
        value: $[ dependencies.Prepare.outputs['ExportPreparation.MainProjectVersion'] ]
      - name: MainProject.PackageName
        value: $[ dependencies.Prepare.outputs['ExportPreparation.MainProjectPackageName'] ]
      - name: MainProject.Description
        value: $[ dependencies.Prepare.outputs['ExportPreparation.MainProjectDescription'] ]
      - name: BuildParameters.HasAffectedBuildProjects
        value: $[ dependencies.Prepare.outputs['ExportPreparation.BuildParameters.HasAffectedBuildProjects'] ]
      - name: BuildParameters.HasAffectedPublishProjects
        value: $[ dependencies.Prepare.outputs['ExportPreparation.BuildParameters.HasAffectedPublishProjects'] ]
    steps:
      - checkout: self
        fetchDepth: 0
        persistCredentials: true

      - template: ../scripts-templates/create-drop-folder.yml@azure-pipelines-repo

      - template: ../scripts-templates/calculate-target-frameworks-dotnet.yml@azure-pipelines-repo
        parameters:
          supportedFrameworks: '$(SupportedFrameworks)'
          solutionPattern: '$(BuildParameters.Solution)'
          testProjects: '$(BuildParameters.TestProjects)'
          testEnabled: $(TestEnabled)
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - template: ../scripts-templates/calculate-release-version.yml@azure-pipelines-repo
        parameters:
          projectVersion: '$(MainProject.Version)'
          calculateAssemblyVersion: true
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - template: ../scripts-templates/apply-release-version-dotnet.yml@azure-pipelines-repo
        parameters:
          workingDirectory: '$(Build.SourcesDirectory)'
          solutionPattern: '$(BuildParameters.Solution)'
          forceVersion: '$(ForceVersion)'
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - template: ../scripts-templates/set-output-filename.yml@azure-pipelines-repo
        parameters:
          workingDirectory: '$(Build.SourcesDirectory)'
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - template: ../scripts-templates/export-variable-list.yml@azure-pipelines-repo

      - task: FileTransform@2
        inputs:
          folderPath: '$(System.DefaultWorkingDirectory)'
          enableXmlTransform: false
          xmlTransformationRules: ''
          jsonTargetFiles: '**/appsettings.json'
        condition: and(succeeded(), or(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true')), ne(variables['FileTransformEnabled'], 'false'))
        continueOnError: true

      - ${{ each framework in split(variables.SupportedFrameworks, ';') }}:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '${{ framework }}.x'
            includePreviewVersions: false
          displayName: 'UseDotNet ${{ framework }}'
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), ne(variables['BuildParameters.TargetFramework_${{framework}}'], ''))

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '$(BuildParameters.Solution)'
          feedsToUse: '$(Solution.NugetFeedToUse)'
          nugetConfigPath: '$(Solution.NugetConfig)'
          externalFeedCredentials: '$(ExternalFeedValue)'
        condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - template: ../scripts-templates/audit-cancellation-dotnet.yml@azure-pipelines-repo
        parameters:
          sourcesDirectory: '$(Build.SourcesDirectory)'
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ if ne(parameters.Analyze, 'disabled') }} :
        - task: SonarCloudPrepare@3
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'hfrances-github'
            scannerMode: 'dotnet'
            projectKey: '$(BuildParameters.ProjectKey)'
            projectName: '$(BuildParameters.ProjectName)'
            projectVersion: '$(MainProject.Version)'
            extraProperties: |
              sonar.exclusions=**/obj/**,**/*.dll
              sonar.coverage.exclusions=**/test/**,**/tests/**,**/*Test*/**
              sonar.dotnet.excludeTestProjects=true
              sonar.cs.opencover.reportsPaths=**/*.[Oo]pencover.xml,**/[Oo]pencover.xml
              sonar.cs.cobertura.reportsPaths=**/*.[Cc]obertura.xml,**/[Cc]obertura.xml
              sonar.cs.vscoveragexml.reportsPaths=**/*.[Cc]overagexml,**/*[Cc]overagexml
              sonar.cs.dotcover.reportsPaths=**/*.html
              sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx
          condition: and(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables.SonarQubeEnabled, 'true'))

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '$(BuildParameters.RestoreBuildProjects)'
          arguments: '--configuration $(BuildConfiguration) --no-restore'
        condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ if ne(parameters.Test, 'disabled') }} :
        - task: DotNetCoreCLI@2
          displayName: 'Test + Coverage'
          inputs:
            command: test
            projects: '$(BuildParameters.TestProjects)'
            arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=".*\.Test[s]?\..*" /p:CoverletOutput="$(Build.SourcesDirectory)/TestResults/"'
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ if ne(parameters.Test, 'disabled') }} :
        - template: ../scripts-templates/check-test-projects-dotnet.yml@azure-pipelines-repo
          parameters:
            testResultsDirectory: '$(Build.SourcesDirectory)/TestResults'
            condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ if ne(parameters.Test, 'disabled') }} :
        - task: reportgenerator@4
          inputs:
            reports: '**/*.[Oo]pencover.xml;**/[Oo]pencover.xml;*.[Oo]pencover.xml;[Oo]pencover.xml'
            targetdir: '$(Build.SourcesDirectory)/TestResults/'
          continueOnError: true
          condition: and(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables.HasTests, 'true'))
          displayName: 'Coverage: Parse format'

      - ${{ if ne(parameters.Test, 'disabled') }} :
        - template: ../scripts-templates/collect-coverage-files.yml@azure-pipelines-repo
          parameters:
            condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ if ne(parameters.Test, 'disabled') }} :
        - task: PublishCodeCoverageResults@2
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(CoverageResults)'
          continueOnError: true
          condition: and(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables.HasTests, 'true'))
          displayName: 'Coverage: Publish report'

      - ${{ if ne(parameters.Analyze, 'disabled') }} :
        - task: SonarCloudAnalyze@3
          condition: and(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables.SonarQubeEnabled, 'true'))
        - task: SonarCloudPublish@3
          inputs:
            pollingTimeoutSec: '300'
          condition: and(eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'), eq(variables.SonarQubeEnabled, 'true'))

      - template: ../scripts-templates/mark-build-published.yml@azure-pipelines-repo
        parameters:
          tag: compiled
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedBuildProjects'], 'true'))

      - ${{ each framework in split(variables.SupportedFrameworks, ';') }}:
        - task: DotNetCoreCLI@2
          displayName: Publish ${{ framework }}
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '$(BuildParameters.RestoreBuildProjects)'
            arguments: '--configuration $(BuildConfiguration) --framework $(BuildParameters.TargetFramework_${{framework}}) --output $(BuildParameters.OutputDirectory)/$(BuildParameters.TargetFramework_${{ framework }})'
            modifyOutputPath: false
            zipAfterPublish: false
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'), ne(variables['BuildParameters.TargetFramework_${{framework}}'], ''))

      - task: DeleteFiles@1
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)/output/'
          Contents: 'CodeCoverage'
        displayName: Delete CoverageCode folder
        condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'))

      - task: ArchiveFiles@2
        name: ZipArtifactsDev
        inputs:
          rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/output'
          includeRootFolder: false
          archiveType: 'tar'
          tarCompression: 'gz'
          archiveFile: '$(Build.ArtifactStagingDirectory)/build/$(BuildParameters.OutputFile)'
          replaceExistingArchive: true
        displayName: Package output files
        condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'))

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
        condition: succeededOrFailed()

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact: build'
        inputs:
          artifactName: 'build'
          targetPath: '$(Build.ArtifactStagingDirectory)/build/$(BuildParameters.OutputFile)'
        condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'))

      - ${{ if parameters.SupportsUniversalPackages }} :
        - task: UniversalPackages@0
          displayName: Universal Publish
          inputs:
            command: publish
            publishDirectory: '$(Build.ArtifactStagingDirectory)/output'
            vstsFeedPublish: 'universal-packages'
            vstsFeedPackagePublish: '$(MainProject.PackageName)'
            packagePublishDescription: '$(MainProject.Description)'
            versionOption: custom
            versionPublish: '$(BuildParameters.DockerVersion)'
          continueOnError: false
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'), eq(variables['PublishEnabled'], 'true'))

        - template: ../scripts-templates/mark-build-published.yml@azure-pipelines-repo
          parameters:
            tag: published
            condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'), eq(variables['PublishEnabled'], 'true'))

      - ${{ if parameters.SupportsContainers }} :
        - task: Docker@2
          displayName: 'Docker: Build and Push'
          inputs:
            command: 'buildAndPush'
            containerRegistry: '$(ContainerRegistry)'
            repository: '$(ContainerName)'
            Dockerfile: '**/Dockerfile'
            buildContext: '$(Build.ArtifactStagingDirectory)/output'
            tags: |
              $(BuildParameters.DockerVersion)
              $(BuildParameters.DockerAlias)
          condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'), ne(variables.ContainerRegistry, ''), ne(variables.ContainerName, ''), eq(variables['PublishDocker'], 'true'))

        - template: ../scripts-templates/mark-build-published.yml@azure-pipelines-repo
          parameters:
            tag: published
            condition: and(succeeded(), eq(variables['BuildParameters.HasAffectedPublishProjects'], 'true'), ne(variables.ContainerRegistry, ''), ne(variables.ContainerName, ''), eq(variables['PublishDocker'], 'true'))
