parameters:
  - name: stageName
    type: string
    default: Stage
  - name: displayName
    type: string
    default: ''
  - name: conditionalStage
    type: string
  - name: conditionalJob
    type: string
  - name: conditionalTask
    type: string
    default: 'SetOutputs'
  - name: conditionalVariable
    type: string
  - name: mappingVariables
    type: object
    default: {}
  - name: additionalVariables
    type: object
    default: {}
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()
  - name: jobs
    type: jobList
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ coalesce(parameters.displayName, parameters.stageName) }}

    variables:
      # 1. Inject direct additional variables
      - ${{ each pair in parameters.additionalVariables }}:
        - name: ${{ pair.key }}
          value: ${{ pair.value }}
      # 2. Dependency resolution (mappingVariables)
      - ${{ each pair in parameters.mappingVariables }}:
        - name: ${{ coalesce(pair.value, pair.key) }}
          value: $[ stageDependencies.${{ parameters.conditionalStage }}.${{ parameters.conditionalJob }}.outputs['${{ parameters.conditionalTask }}.${{ pair.key }}'] ]
      # 3. Parent Summary Variable
      - name: ${{ parameters.conditionalVariable }}
        value: $[ stageDependencies.${{ parameters.conditionalStage }}.${{ parameters.conditionalJob }}.outputs['${{ parameters.conditionalTask }}.${{ parameters.conditionalVariable }}'] ]

    dependsOn:
      - ${{ parameters.conditionalStage }}
      - ${{ each dep in parameters.dependsOn }}:
        - ${{ dep }}

    # Dynamic condition using direct dependency
    condition: and(${{ parameters.condition }}, eq(dependencies.${{ parameters.conditionalStage }}.outputs['${{ parameters.conditionalJob }}.${{ parameters.conditionalTask }}.${{ parameters.conditionalVariable }}'], 'true'))

    # =========================================================
    # Inject the real jobs
    # =========================================================    
    jobs: ${{ parameters.jobs }}
